# Generated by Django 4.2.3 on 2023-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=20)),
                ("vnumber", models.CharField(max_length=20)),
                ("vtype", models.CharField(max_length=10)),
                ("pwd", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
