# Generated by Django 4.2.3 on 2023-08-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rideapp", "0002_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("ride_cost", models.IntegerField(default=-1)),
                ("cust_rate", models.IntegerField(default=-1)),
                (
                    "booked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rideapp.customer",
                    ),
                ),
                (
                    "serviced_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rideapp.driver",
                    ),
                ),
            ],
        ),
    ]
