# Generated by Django 4.2.3 on 2023-08-06 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rideapp", "0003_ride"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="fname", new_name="firstname",
        ),
        migrations.RenameField(
            model_name="customer", old_name="lname", new_name="lastname",
        ),
        migrations.RenameField(
            model_name="customer", old_name="pwd", new_name="password",
        ),
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
