# Generated by Django 4.2.3 on 2023-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideapp", "0004_rename_fname_customer_firstname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver", old_name="fname", new_name="firstname",
        ),
        migrations.RenameField(
            model_name="driver", old_name="lname", new_name="lastname",
        ),
        migrations.RenameField(
            model_name="driver", old_name="pwd", new_name="password",
        ),
        migrations.RenameField(model_name="driver", old_name="vtype", new_name="role",),
        migrations.RenameField(
            model_name="driver",
            old_name="vnumber",
            new_name="vehicleregistrationnumber",
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicletype",
            field=models.CharField(default="driver", max_length=10),
            preserve_default=False,
        ),
    ]
